import numpy as np
a = np.arange(1,10)
# print(a)
# print(a[:3])
# print(a[3:6])
# print(a[6:])
# print(a[::-1])
# print(a[:-4:-1])
# print(a[-4:-7:-1])
# print(a[-7::-1])
# print(a[::])
# print(a[::3])
# print(a[1::3])
# print(a[2::3])

a.resize(3,3)
print(a[1:,:])
print(a[2:,:])
print(a[1:,1:])
print(a[1:,2:])
print(a[1:,0:2])
