f=open('/home/tarena/aid1808/pbase/day16/code/data1.txt','rb')
b=f.read(3)
print('您读取的是：',b)
print('当前的读写位置是',f.tell())
# f.seek(5,0)
# f.seek(2,1)
f.seek(-15,2)
print("当前的读写位置是：",f.tell())
b=f.read(5)
print('读取的内容是',b)
f.close()